name: icapps_icons
description: "A package that cointains the icapps icons."
version: 1.1.0
homepage: https://github.com/icapps/flutter_icapps_icons

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: icappsIcons
      fonts:
        - asset: lib/fonts/icappsIcons.ttf