name: icon_parser
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  flutter:
    sdk: flutter
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
